-- AlterTable
ALTER TABLE "User" ADD COLUMN "phone" STRING,
ADD COLUMN "role" STRING NOT NULL DEFAULT 'member',
ADD COLUMN "phoneVerifyCode" STRING,
ADD COLUMN "phoneVerifyExpiry" TIMESTAMP(3),
ADD COLUMN "lastActivityAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
